name: publish
on: push
jobs:
  publish:
    name: run
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/core:2.9
      options: --entrypoint=sh
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: 'Build'
        run: |
          make init
          make all
          make clean
      - name: 'Publish'
        run: |
          git config --global user.name 'crispbot'
          git config --global user.email 'crispgm@users.noreply.github.com'
          git add .
          git commit --allow-empty -m "Auto published at $(date +%Y%m%d-%H:%M:%S)"
          git remote set-url --push origin https://crispgm:${{ secrets.ACCESS_TOKEN }}@github.com/crispgm/wiki-base
          git push origin gh-pages
